# -*- coding: utf-8 -*-
"""sirassignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sR1Uww3s4z61bjRkla2r3-4gGNb3pj4R
"""



"""# Q1 Given a two list. Create a third list by picking an odd-index element fromthe first list and even index elements from the second"""

list1 = [3,6,9,12,15,18,21]
list2 = [4,8,12,16,20,24,28]
a = list1[1::2]
print("Element at odd-index from list one",a)
b = list2[0::2]
print("Element at even-index from list two",b)
a.extend(b)
print("Printing final third list")
a

"""# Q2 Given a number count the total number of digits in a number"""

count=0
no = int (input("enter the number"))
while no>0:
    rem=no%10
    no=no//10
    count+=1
print("The total no of digits in a given no are",count)

"""# Q3 Write a python program to print the numbers of a specified list after removing even numbers from it"""

a = [25,70,62,71,36,65,18,99,27,82]
b=[]
for i in a:
    if i%2==1:
        b.append(i)
print(b)

"""# Q4 Write a python program to generate and print a list of first and last 5 elements where the values are square of numbers between 1 and 30 (both included ) """

no=1
a = []
while no<31:
    b=no**2
    a.append(b)
    no+=1
print(a) 
c=int(input("Enter the value of how many elements of starting to be printed"))
b = a[0:c:1]
print("Your first",c,"elements are",b)
d=int(input("Enter the value of how many elements of end to be printed "))
e = a[-d::]
print("Your last",d,"elements are",e)

"""Q5 Write a python program to generate all permutations of a list in python"""

list1=[1,2,3]
print("original list: ",list1)
list2=[]
for i in list1:
    for j in list1:
         for k in list1:
                list2.append([i] + [j] + [k])
print("\n all possible permutation: ",list2)

"""Q6 Write a python program to check whether two lists are circularly identical

       

"""

x=[3,4,1,2]
y=[1,2,3,4]
a=0
b=0
while True:
    c=x[0]
    x.pop(0)
    x.append(c)
    b=len(y)
    a+=1
    if x==y:
        print ('identical')
        break
    if a==b:
        print ('not identical')
        break

"""# Q7 Write a program to change the position of every n-th value with the (n+1)th in a list """

a = [0,1,2,3,4,5]
for i in range(0,len(a),2):
    a[i],a[i+1] = a[i+1],a[i]
print(a)

"""# Q8 Write a python program to iterate over two lists simultaneously"""

a = [1,2,3,4,5]
b = [6,7,8,9,10]
c = []
j=0
for i in a:
    c.append(i)
    c.append(b[j])
    j+=1
c

"""Que.9.Write a Python program to generate the combinations of n distinct objects taken from the elements of a given list. Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9] Combinations of 2 distinct objects: [1, 2] [1, 3] [1, 4] [1, 5] .... [7, 8] [7, 9] [8, 9]

"""

a=[1,2,3,4,5,6,7,8,9]
c=[]
for i in a:
  for j in a:
    b=[]
    if (i == j):
      pass
    elif i != j:
      b.append(i)
      b.append(j)
      c.append(b)
print("Combination of distinct elements are: ",c)

"""# Q10 Write a python program to remove duplicates from a list of list"""

list1=[[10,20],[40],[30,56,25],[10,20],[33]]
list2=[]
for i in list1:
    if i not in list2:
        list2.append(i)

print(list2)

